modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL="https://github.com/unilock/ClientBuildersWandTwo/issues"

[[mods]]
modId = "clientbuilderswandtwo"
version = "${version}"

displayName = "Client Builder's Wand 2.0"
displayURL="https://github.com/unilock/ClientBuildersWandTwo"
logoFile = "icon.png"
authors = "unilock, waechter_von_atlantis"
description = '''
Client-side mod to allow building as if you had a "Builder's Wand" from [insert mod here]

Rewrite of "Client Builders Wand" by waechter_von_atlantis (licensed under the MIT License)
https://www.curseforge.com/minecraft/mc-mods/client-builders-wand
'''

[[dependencies.clientbuilderswandtwo]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clientbuilderswandtwo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clientbuilderswandtwo]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.0,)"
ordering = "NONE"
side = "CLIENT"
